# Generated by Django 5.1.7 on 2025-03-30 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True, verbose_name='Area')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mov', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de movimiento')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'db_table': 'Movimiento',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(choices=[('T1 - (BOG)', 'T1 - (BOG)'), ('T2 - (MDE)', 'T2 - (MDE)'), ('T3 - (CLO)', 'T3 - (CLO)'), ('T4 - (BAQ)', 'T4 - (BAQ)'), ('T5 - (CTG)', 'T5 - (CTG)'), ('T6 - (BGA)', 'T6 - (BGA)'), ('T7 - (CUC)', 'T7 - (CUC)'), ('T8 - (PEI)', 'T8 - (PEI)')], default='Bogotá ()', max_length=50, verbose_name='Ciudad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 'terminales',
                'db_table': 'Terminal',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Número de documento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña')),
                ('conf_contrasena', models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Código')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('modalidad', models.CharField(choices=[('PR', 'Presencial'), ('RM', 'Remoto'), ('ES', 'En sitio')], default='PR', max_length=2, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.area', verbose_name='Area')),
                ('id_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'agente',
                'verbose_name_plural': 'agentes',
                'db_table': 'Agente',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.PositiveIntegerField(unique=True, verbose_name='Activo')),
                ('nomenclatura', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nomenclatura')),
                ('categoria', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Pantalla', 'Pantalla')], default='PC', max_length=50, verbose_name='Categoría')),
                ('renting', models.BooleanField(default=False, verbose_name='Renting')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=50, unique=True, verbose_name='N. de serie')),
                ('observaciones', models.CharField(max_length=300, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.agente', verbose_name='Agente')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.area', verbose_name='Area')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca', verbose_name='Marca')),
                ('id_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'db_table': 'Activo',
            },
        ),
        migrations.CreateModel(
            name='Detalle_movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Prestamo', 'Prestamo'), ('Asignacion', 'Asignacion'), ('Traslado', 'Traslado'), ('Dispocicion final', 'Dispocicion final')], default='Prestamo', max_length=50, verbose_name='Tipo de movimiento')),
                ('id_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.activo', verbose_name='Activo')),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.agente', verbose_name='Agente')),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'detalle_movimiento',
                'verbose_name_plural': 'detalle_movimientos',
                'db_table': 'Detalle_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(unique=True, verbose_name='Número de documento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña')),
                ('conf_contrasena', models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'db_table': 'Operador',
            },
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('periferico', models.CharField(choices=[('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Diadema', 'Diadema'), ('Base refrigentante', 'Base refrigentante'), ('Speaker', 'Speaker'), ('Camara', 'Camara'), ('Multipuerto', 'Multipuerto'), ('Cable de red', 'Cable de red'), ('Switch etheternet', 'Switch ethernet')], default='Teclado', max_length=50, verbose_name='Periferico')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=50, unique=True, verbose_name='N. de serie')),
                ('observaciones', models.CharField(max_length=300, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.agente', verbose_name='Agente')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.area', verbose_name='Area')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca', verbose_name='Marca')),
                ('id_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'periferico',
                'verbose_name_plural': 'perifericos',
                'db_table': 'Periferico',
            },
        ),
    ]
