# Generated by Django 5.2 on 2025-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Mantenimiento'),
        ),
        migrations.AddField(
            model_name='detalle_movimiento',
            name='mantenimiento',
            field=models.BooleanField(default=False, verbose_name='Mantenimiento'),
        ),
    ]
