# Generated by Django 5.1.7 on 2025-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_periferico'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Periférico', 'Periférico')], default='Activo', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='categoria',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Pantalla', 'Pantalla'), ('Diadema', 'Diadema'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Base Refrigerante', 'Base Refrigerante'), ('Speaker', 'Speaker')], default='PC', max_length=50, verbose_name='Categoría'),
        ),
    ]
