# Generated by Django 5.2 on 2025-04-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_movimiento',
            name='mantenimiento',
        ),
    ]
