# Generated by Django 5.2 on 2025-04-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_detalle_movimiento_mantenimiento'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='responsable_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='responsable_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
