# Generated by Django 5.1.7 on 2025-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_activo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.BooleanField(default=True, verbose_name='Tipo'),
        ),
    ]
