# Generated by Django 5.1.7 on 2025-03-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_activo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='activo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Activo'),
        ),
    ]
