# Generated by Django 5.1.7 on 2025-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_activo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='categoria',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Diadema', 'Diadema'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Base Refrigerante', 'Base Refrigerante')], max_length=50, verbose_name='Categoría'),
        ),
    ]
